### ISSUE TITLE
What is the maximum resolution supported by v2.5? How much can be set for scale_resolution？

### ISSUE THREAD

**Issue by zweiqi** [OpenBMB/MiniCPM-V#158]

**Comment by Cuiunbo** [comment]
The maximum resolution we support now is 1344*1344, and you can scale to any size as long as the GPU memory can handle it!

**Comment by YuzaChongyi** [comment]
If you want to support larger resolution， you can set the `max_slice_nums` to a larger number. it is now set to 9, supporting a maximum of 9 * 448 * 448 pixels (equals to `1344* 1344`). If set to 16, it can support 16 * 448 * 448 pixels (equals to `1792 * 1792 `). 

We do not recommend changing the value of `scale_resolution`, because 448 is the size of our pretraining, the vision encoder has been fully trained at this resolution
