### ISSUE TITLE
convert model to gguf failed[llamacpp] - <title>

### ISSUE THREAD

**Issue by yancaoweidaode** [OpenBMB/MiniCPM-V#404]
### 摘要 | Summary

File not found: path/model/tokenizer.model, Cannot find Llama BPE tokenizer

### 基本示例 | Basic Example

python convert_hf_to_gguf.py /path/to/model

### 缺陷 | Drawbacks

File not found: path/model/tokenizer.model, Cannot find Llama BPE tokenizer

**Comment by tc-mb** [comment]
There are two methods:
1. You can use the gguf we transferred first.
2. I have modified python convert_hf_to_gguf.py so far, but this change should not occur after it is merged with pr.
The modification is to add 
```
res = " qwen2 "
```
 to line 426, so that the verification environment in the code can be exceeded and the hook can be used.
