### ISSUE TITLE
Benchmark results of TextVQA

### ISSUE THREAD

**Issue by Cbtor** [OpenBMB/MiniCPM-V#58]
We got different benchmark results while evaluation the MiniCPM-V 2.0 model provided in huggingface. For example, we got only 66 on TextVQA, which is different from 74.1 provided in the technique report. We directly use the `chat` api in modeling_minicpmv.py like this.

```python
        output_ids, context, _ = model.chat(
            image=image_tensor,
            msgs=msgs,
            context=None,
            tokenizer=tokenizer,
            sampling=True,
            temperature=0.7
    	)
```

Would you please provide the detailed hyperparameters for the evaluation?

**Comment by Cuiunbo** [comment]
Hi Cbtor👋, I'm delighted to see that you are trying out MiniCPM-V-2. In order to reproduce the scores reported in our study, you can use the following settings. Additionally, I will publish the evaluation details in the readme to allow more people to directly reference it~

prompt = "Answer the question directly with a single word" + '\n' + question
default_kwargs = {
max_new_tokens: 100,
sampling: False,
num_beams: 3
}

Feel free to contact me if you have any concern😊～

**Comment by Cbtor** [comment]
Thank you for your reply. I tried the prompt and the parameters you provided, but only get 68.62 on TextVQA, while the results of MME benchmark I got are even better than that in your technique report (1850). Could you please provide a simple evaluation script on TextVQA?
